name: Build and Deploy
on: 
  push:
    branches: 
      - master
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      SOURCE_REPO: "15x15G/15x15G.github.io"  # 博客源码仓库
      TARGET_REPO: "15x15G/15x15G.github.io"  # 博客部署仓库
      TARGET_BRANCH: "gh-pages"  # 博客部署的分支名
      SECRET: ${{ secrets.PERSONAL_TOKEN }}
    steps:
    # 配置 git，避免一些莫名其妙的错误
    - name: Git Configuration
      run: |
        git config --global core.quotePath false
        git config --global core.autocrlf false
        git config --global core.safecrlf true
        git config --global core.ignorecase false
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    # 拉取源码
    - name: Clone Repository
      run:
        git clone --branch=master --quiet https://github.com/$SOURCE_REPO site

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist/